# Generated by Django 5.2.8 on 2025-11-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("youtube_video", "YouTube Video"),
                            ("youtube_playlist", "YouTube Playlist"),
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("tv_series", "TV Series"),
                            ("book", "Book"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "Currently Watching/Reading"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("progress", models.IntegerField(default=0)),
                ("total_units", models.IntegerField(default=0)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
